export const INPUTS = [
  {
    id: "username",
    name: "name",
    class: "username",
    label: "Username*",
    type: "text",
    placeholder: "Enter username",
  },
  {
    id: "email",
    name: "email",
    class: "email",
    label: "Email Address*",
    type: "email",
    placeholder: "Enter email address",
  },
  {
    id: "phone__number",
    name: "phoneNumber",
    class: "phone__number",
    label: "Phone Number*",
    type: "text",
    placeholder: "970 598-844-683",
  },
  {
    id: "create__password",
    name: "password",
    class: "create__password",
    label: "Create Password*",
    type: "password",
    placeholder: "password",
  },
  {
    id: "repeat__password",
    name: "repeatePassword",
    class: "create__password",
    label: "Repeat password",
    type: "password",
    placeholder: "Repeat password",
  },
];
